# Generated by Django 3.1.4 on 2020-12-21 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pmanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_member',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Pmanage.user'),
            preserve_default=False,
        ),
    ]
