# Generated by Django 3.1.3 on 2020-12-20 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pmanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Team_Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_members_firstname', models.CharField(max_length=64)),
                ('team_members_lastname', models.CharField(max_length=64)),
                ('team_leader', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='tasks',
            new_name='complete_percentage',
        ),
        migrations.AddField(
            model_name='project',
            name='task',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bugs', models.TextField()),
                ('percentage', models.IntegerField()),
                ('Tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pmanage.tasks')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.IntegerField()),
                ('Temid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pmanage.team_member')),
            ],
        ),
        migrations.AddField(
            model_name='tasks',
            name='Pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pmanage.project'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(max_length=65)),
                ('proid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pmanage.project')),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_status', models.CharField(max_length=64)),
                ('proid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pmanage.project')),
            ],
        ),
    ]
