# Generated by Django 3.1.3 on 2020-12-20 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pmanage', '0002_auto_20201220_0426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='report',
            new_name='Error Description',
        ),
    ]
