# Generated by Django 3.1.4 on 2020-12-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pmanage', '0002_team_member_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='task_count',
        ),
    ]
