# Generated by Django 3.1.3 on 2020-12-20 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pmanage', '0003_auto_20201220_0439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='task',
            new_name='task_count',
        ),
    ]
