# Generated by Django 3.1.3 on 2020-12-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pmanage', '0004_auto_20201220_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='max_day',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
