# Generated by Django 3.1.3 on 2020-12-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pmanage', '0005_auto_20201223_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='unreleased', max_length=64),
            preserve_default=False,
        ),
    ]
