# Generated by Django 3.1.3 on 2020-12-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pmanage', '0006_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='unrelease', max_length=64),
        ),
    ]
