# Generated by Django 3.1.3 on 2020-12-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pmanage', '0008_auto_20201226_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='Error Description',
            new_name='Report',
        ),
    ]
