# Generated by Django 3.1.4 on 2020-12-28 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pmanage', '0009_auto_20201228_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='Report',
            new_name='Reports',
        ),
    ]
